// <auto-generated />
namespace MyExample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial));
        
        string IMigrationMetadata.Id
        {
            get { return "201502050807258_initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
