// <auto-generated />
namespace MyExample.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class MovieContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201502050810438_MovieContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
